#ifndef _GAME_DISP_H
#define _GAME_DISP_H

#define HU_DISP_WIDTH 576.0f
#define HU_DISP_WIDTHI ((int)HU_DISP_WIDTH)
#define HU_DISP_HEIGHT 480.0f
#define HU_DISP_HEIGHTI ((int)HU_DISP_HEIGHT)
#define HU_DISP_ASPECT (HU_DISP_WIDTH/HU_DISP_HEIGHT)

#define HU_DISP_CENTERXI (HU_DISP_WIDTHI/2)
#define HU_DISP_CENTERX (HU_DISP_WIDTH/2)
#define HU_DISP_CENTERYI (HU_DISP_HEIGHTI/2)
#define HU_DISP_CENTERY (HU_DISP_HEIGHT/2)

#define HU_FB_WIDTH 640
#define HU_FB_HEIGHT 480

#endif