#ifndef MSM_SE_H
#define MSM_SE_H

#define MSM_SE_MARIO 142
#define MSM_SE_LUIGI 112
#define MSM_SE_PEACH 292
#define MSM_SE_YOSHI 412
#define MSM_SE_WARIO 352
#define MSM_SE_DAISY 52
#define MSM_SE_WALUIGI 382
#define MSM_SE_KINOPIO 82
#define MSM_SE_TERESA 322
#define MSM_SE_MINIKOOPA 262
#define MSM_SE_MINIKOOPAR 232
#define MSM_SE_MINIKOOPAG 202
#define MSM_SE_MINIKOOPAB 172

#define MSM_SE_VOICE_MARIO 502
#define MSM_SE_VOICE_LUIGI 482
#define MSM_SE_VOICE_PEACH 602
#define MSM_SE_VOICE_YOSHI 682
#define MSM_SE_VOICE_WARIO 642
#define MSM_SE_VOICE_DAISY 442
#define MSM_SE_VOICE_WALUIGI 662
#define MSM_SE_VOICE_KINOPIO 462
#define MSM_SE_VOICE_TERESA 622
#define MSM_SE_VOICE_MINIKOOPA 582
#define MSM_SE_VOICE_MINIKOOPAR 562
#define MSM_SE_VOICE_MINIKOOPAG 542
#define MSM_SE_VOICE_MINIKOOPAB 522

#endif