#ifndef DATANUM_WIN_H
#define DATANUM_WIN_H

#include "datadir_enum.h"

enum {
    WIN_ANM_font = DATANUM(DATA_win, 0),
    WIN_ANM_cursor = DATANUM(DATA_win, 1),
    WIN_ANM_icon = DATANUM(DATA_win, 2),
    WIN_ANM_cardA = DATANUM(DATA_win, 3),
    WIN_ANM_cardB = DATANUM(DATA_win, 4),
    WIN_ANM_frame1 = DATANUM(DATA_win, 5),
    WIN_ANM_frame2 = DATANUM(DATA_win, 6),
    WIN_ANM_frame3 = DATANUM(DATA_win, 7),
    WIN_ANM_frame4 = DATANUM(DATA_win, 8),
    WIN_ANM_talkChorl = DATANUM(DATA_win, 9),
    WIN_ANM_talkNerl = DATANUM(DATA_win, 10),
    WIN_ANM_talkTerl = DATANUM(DATA_win, 11),
    WIN_ANM_talkNirl = DATANUM(DATA_win, 12),
    WIN_ANM_talkHarl = DATANUM(DATA_win, 13),
    WIN_ANM_talkMarl = DATANUM(DATA_win, 14),
    WIN_ANM_talkDarl = DATANUM(DATA_win, 15),
    WIN_ANM_talkKoopa = DATANUM(DATA_win, 16),
    WIN_ANM_talkKuribo = DATANUM(DATA_win, 17),
    WIN_ANM_talkHeyho = DATANUM(DATA_win, 18),
    WIN_ANM_talkNoko2 = DATANUM(DATA_win, 19),
    WIN_ANM_talkJugem = DATANUM(DATA_win, 20),
    WIN_ANM_talkWan2 = DATANUM(DATA_win, 21),
    WIN_ANM_talkUkki = DATANUM(DATA_win, 22),
    WIN_ANM_talkPata2 = DATANUM(DATA_win, 23),
    WIN_ANM_talkHanachan = DATANUM(DATA_win, 24),
    WIN_ANM_talkHanachan2 = DATANUM(DATA_win, 25),
    WIN_ANM_talkKamekku = DATANUM(DATA_win, 26),
    WIN_ANM_talkKokamekku = DATANUM(DATA_win, 27),
    WIN_ANM_talkChoro = DATANUM(DATA_win, 28),
    WIN_ANM_talkCapMachine = DATANUM(DATA_win, 29),
    WIN_ANM_talkPuku2 = DATANUM(DATA_win, 30),
    WIN_ANM_talkBattan = DATANUM(DATA_win, 31),
    WIN_ANM_talkDossun = DATANUM(DATA_win, 32),
    WIN_ANM_saveIcon1 = DATANUM(DATA_win, 33),
    WIN_ANM_saveIcon2 = DATANUM(DATA_win, 34),
    WIN_ANM_saveIcon3 = DATANUM(DATA_win, 35),
    WIN_ANM_saveIcon4 = DATANUM(DATA_win, 36),
    WIN_ANM_saveBanner = DATANUM(DATA_win, 37),
    WIN_ANM_saveBgBoard = DATANUM(DATA_win, 38),
    WIN_ANM_saveBgStory = DATANUM(DATA_win, 39),
    WIN_ANM_saveBgSd = DATANUM(DATA_win, 40),
    WIN_ANM_saveBgMode = DATANUM(DATA_win, 41),
    WIN_ANM_wipeStar = DATANUM(DATA_win, 42),
    WIN_ANM_wipeKoopa = DATANUM(DATA_win, 43),
    WIN_ANM_wipeWave = DATANUM(DATA_win, 44),
    WIN_ANM_cardChoice = DATANUM(DATA_win, 45),
};

#endif